language: python
python:
  - "3.5"
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=rsl setup.py test
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
